# This file was generated by GoReleaser. DO NOT EDIT.
cask "projectforge" do
  name "projectforge"
  desc "Project Forge creates and manages applications written in the Go programming language. Using code generation, the latest technology, and a strong standard library, Project Forge will help manage your project's code, assets, UI and UX."
  homepage "https://projectforge.dev"
  version "2.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projectforge"

  on_macos do
    on_intel do
      url "https://github.com/kyleu/projectforge/releases/download/v#{version}/projectforge_#{version}_darwin_amd64.zip"
      sha256 "d23ac0750547938fee404e817d210b9b2ee9b7c65b763eb695e0dc73ab952a85"
    end
    on_arm do
      url "https://github.com/kyleu/projectforge/releases/download/v#{version}/projectforge_#{version}_darwin_arm64.zip"
      sha256 "738d8d862adaf75ee197e786cb88e57be565e9ae71e80fdcc5856f98e5be9603"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kyleu/projectforge/releases/download/v#{version}/projectforge_#{version}_linux_amd64.zip"
      sha256 "41c1573b33a271883f068052e2ab1ed051ff90907d35d63f2d18cb4f1d663c6e"
    end
    on_arm do
      url "https://github.com/kyleu/projectforge/releases/download/v#{version}/projectforge_#{version}_linux_arm64.zip"
      sha256 "49d58a46f1eb854b5905346c32d5247909860f6dc701bb76f1da065c3c423875"
    end
  end

  # No zap stanza required
end
