# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Admini < Formula
  desc "Explore and manage your data as fast and easily as possible. Supports PostgreSQL, MySQL, and SQLite data sources, and provides a lightning-fast web interface"
  homepage "https://admini.dev"
  version "0.4.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/admini/releases/download/v0.4.9/admini_0.4.9_darwin_arm64.zip"
      sha256 "0900c7e27471f7895d43cce10e8f679c744a1d8fb5702a80c9ffab2a16fc9825"

      def install
        bin.install "admini"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/admini/releases/download/v0.4.9/admini_0.4.9_darwin_amd64.zip"
      sha256 "5a3bc4a65c8a4e606b66c54e4cdc2f17d0144c82bb17c51a436cfa952b332859"

      def install
        bin.install "admini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/admini/releases/download/v0.4.9/admini_0.4.9_linux_armv6.zip"
      sha256 "b0e13b3a19702fe10c1a924e7550831678931d146c0e37fd0fbe486fa756232a"

      def install
        bin.install "admini"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/admini/releases/download/v0.4.9/admini_0.4.9_linux_amd64.zip"
      sha256 "7b733f79a1001a7fb711710db4e895b257f86e40a7edf755dfa5531c4601531e"

      def install
        bin.install "admini"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/admini/releases/download/v0.4.9/admini_0.4.9_linux_arm64.zip"
      sha256 "db3f91dd9ce3c715b154a87aa3dd7ce847b89849d519283424cd5c644c55c6a6"

      def install
        bin.install "admini"
      end
    end
  end
end
