# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Admini < Formula
  desc "Explore and manage your data as fast and easily as possible. Supports PostgreSQL, MySQL, and SQLite data sources, and provides a lightning-fast web interface"
  homepage "https://admini.dev"
  version "0.5.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/admini/releases/download/v0.5.7/admini_0.5.7_darwin_amd64.zip"
      sha256 "27e214879b75780c156d24c5aebd6edb5a5872772131c01bd1c83a09ac07efaf"

      def install
        bin.install "admini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/admini/releases/download/v0.5.7/admini_0.5.7_darwin_arm64.zip"
      sha256 "87f67d78f9e1271032fc12e539a8db13bef45513ecf5458e19d7a1081e6d5776"

      def install
        bin.install "admini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/admini/releases/download/v0.5.7/admini_0.5.7_linux_amd64.zip"
        sha256 "154ef7d120de5f1b26c851800054823c05ef9f1601752bc39ac7e2c1652dc50b"

        def install
          bin.install "admini"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/admini/releases/download/v0.5.7/admini_0.5.7_linux_armv6.zip"
        sha256 "3e851b9ee75c1ec5b1eb779b80072e42ad2d3666ba0f25b6e0d6eff68f649adc"

        def install
          bin.install "admini"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/admini/releases/download/v0.5.7/admini_0.5.7_linux_arm64.zip"
        sha256 "39977545b035f5760e27b657d81adc79b703e5ab28fd126e382be4b7f3bf7c3f"

        def install
          bin.install "admini"
        end
      end
    end
  end
end
