# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbaudit < Formula
  desc "Allows you to visualize the activity on your SQL Server installation"
  homepage "https://github.com/kyleu/dbaudit"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/dbaudit/releases/download/v0.0.1/dbaudit_0.0.1_darwin_arm64.zip"
      sha256 "5c71b50c2689cfe7eb49f78778381edcd68704a41e01defc5af31924e26558a5"

      def install
        bin.install "dbaudit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/dbaudit/releases/download/v0.0.1/dbaudit_0.0.1_darwin_amd64.zip"
      sha256 "5b18b76d2c8b53aff1535565ef26647f0c1a017359b601f71ae83ff2e4047686"

      def install
        bin.install "dbaudit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/dbaudit/releases/download/v0.0.1/dbaudit_0.0.1_linux_arm64.zip"
      sha256 "22f6dd14297d79c3c885e3723e57c72aeb05674713d8d3e0110e4d786a6476dc"

      def install
        bin.install "dbaudit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/dbaudit/releases/download/v0.0.1/dbaudit_0.0.1_linux_amd64.zip"
      sha256 "e7ba81b67f68e138e1454ea60e754ac8dfc4bba0d3a2ff10a2190aeb548a6c4d"

      def install
        bin.install "dbaudit"
      end
    end
  end
end
