# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idled < Formula
  desc "Very much a work-in-progress, this will eventually be an incremental/idle game"
  homepage "https://github.com/kyleu/idled"
  version "0.0.2"
  license "CC0"

  on_macos do
    on_intel do
      url "https://github.com/kyleu/idled/releases/download/v0.0.2/idled_0.0.2_darwin_amd64.zip"
      sha256 "a2a2f96a056bd25ca71cac6d3184fc67e4d8b002403442594eba93d9097dd20b"

      def install
        bin.install "idled"
      end
    end
    on_arm do
      url "https://github.com/kyleu/idled/releases/download/v0.0.2/idled_0.0.2_darwin_arm64.zip"
      sha256 "aa9dac37c792f75ca95422ffbb44df609d3bf260437a6a613378870899f857c0"

      def install
        bin.install "idled"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.2/idled_0.0.2_linux_amd64.zip"
        sha256 "735a0b95785899ec7de40dbd73bbb3fe5e777321a4567620dcf9df0da785dd7d"

        def install
          bin.install "idled"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.2/idled_0.0.2_linux_armv6.zip"
        sha256 "ff62a9bda3efa21911a93f50d8948263404ec08cf5a805d68d1631d5e2011ade"

        def install
          bin.install "idled"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.2/idled_0.0.2_linux_arm64.zip"
        sha256 "9c0a58a3625995eb10841be13e99ca6aec5fc5182fe12b796151fdd1c001fa27"

        def install
          bin.install "idled"
        end
      end
    end
  end
end
