# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idled < Formula
  desc "Very much a work-in-progress, this will eventually be an incremental/idle game"
  homepage "https://github.com/kyleu/idled"
  version "0.0.3"
  license "CC0"

  on_macos do
    on_intel do
      url "https://github.com/kyleu/idled/releases/download/v0.0.3/idled_0.0.3_darwin_amd64.zip"
      sha256 "b978814452738ba1bbe96e43ac571474208f99baa2ba5fc116bb8ac7a879eb37"

      def install
        bin.install "idled"
      end
    end
    on_arm do
      url "https://github.com/kyleu/idled/releases/download/v0.0.3/idled_0.0.3_darwin_arm64.zip"
      sha256 "8636322f7c0f0d689d05e484ea447bc27386c3ef8e1f766620ba99a8e7c3d787"

      def install
        bin.install "idled"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.3/idled_0.0.3_linux_amd64.zip"
        sha256 "e5e915f3753fe9087e4fdf90bcf3444d48bfcf1dfed8484564075d8c5dae2dd8"

        def install
          bin.install "idled"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.3/idled_0.0.3_linux_armv6.zip"
        sha256 "0adbf079632eebfdd18ed7182f6c27f912ac3c061187f80fd0f00041213ef1db"

        def install
          bin.install "idled"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.3/idled_0.0.3_linux_arm64.zip"
        sha256 "9ec4b640d87e03cbb3a4ac96bfd2870f188c2c798e4e795dfae318af9793dfef"

        def install
          bin.install "idled"
        end
      end
    end
  end
end
