# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idled < Formula
  desc "Very much a work-in-progress, this will eventually be an incremental/idle game"
  homepage "https://github.com/kyleu/idled"
  version "0.0.4"
  license "CC0"

  on_macos do
    on_intel do
      url "https://github.com/kyleu/idled/releases/download/v0.0.4/idled_0.0.4_darwin_amd64.zip"
      sha256 "a5afa589ae90d4a40704a4d6374e4fda3bf6294ffad8d6222ea20026f07bbb2c"

      def install
        bin.install "idled"
      end
    end
    on_arm do
      url "https://github.com/kyleu/idled/releases/download/v0.0.4/idled_0.0.4_darwin_arm64.zip"
      sha256 "468aa1fc2d1a55a982fcd4e24ac639d9ac3f1c81ebe195ecd09ea4fbe84a07b9"

      def install
        bin.install "idled"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.4/idled_0.0.4_linux_amd64.zip"
        sha256 "dfabd2494202afce7e8a82fc428cae587ebc77c7b076f8c044b5614c5f9ea016"

        def install
          bin.install "idled"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.4/idled_0.0.4_linux_armv6.zip"
        sha256 "dc0f799a62380278d1136bfa9656232f38e5a6eac92ee05f55a1d6331b10aa79"

        def install
          bin.install "idled"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idled/releases/download/v0.0.4/idled_0.0.4_linux_arm64.zip"
        sha256 "2474fb62bc946f38c69b083a78dcb184a909ab3242ef6ee005d9f63dfedf2cfa"

        def install
          bin.install "idled"
        end
      end
    end
  end
end
