# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idlingengine < Formula
  desc "Very much a work-in-progress, this will eventually be an incremental/idle game"
  homepage "https://github.com/kyleu/idlingengine"
  version "0.0.6"
  license "CC0"

  on_macos do
    on_intel do
      url "https://github.com/kyleu/idlingengine/releases/download/v0.0.6/idlingengine_0.0.6_darwin_amd64.zip"
      sha256 "1eff4643691f2b393b94fe216325730f1d59f0341d2cdab946e13a344a7e9843"

      def install
        bin.install "idlingengine"
      end
    end
    on_arm do
      url "https://github.com/kyleu/idlingengine/releases/download/v0.0.6/idlingengine_0.0.6_darwin_arm64.zip"
      sha256 "234fa20bc8b282a33711591916778062174004473ec177b28d5f660cdd5924fd"

      def install
        bin.install "idlingengine"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idlingengine/releases/download/v0.0.6/idlingengine_0.0.6_linux_amd64.zip"
        sha256 "5bf65ae2cc91898d271ffdf2d6b06e31dffa2a9b099b886c757ae2899fb26319"

        def install
          bin.install "idlingengine"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idlingengine/releases/download/v0.0.6/idlingengine_0.0.6_linux_armv6.zip"
        sha256 "33914c35adb14b37c099da71e5ab187f5da1bb03b043c15a7561aaf0b72e6dc9"

        def install
          bin.install "idlingengine"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idlingengine/releases/download/v0.0.6/idlingengine_0.0.6_linux_arm64.zip"
        sha256 "826a7ac3fa4d2aa232a8e2b906a5b5352dd63c09dcb028c1ab647e943876c375"

        def install
          bin.install "idlingengine"
        end
      end
    end
  end
end
