# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idlingengine < Formula
  desc "Very much a work-in-progress, this will eventually be an incremental/idle game"
  homepage "https://github.com/kyleu/idlingengine"
  version "0.0.15"
  license "CC0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/idlingengine/releases/download/v0.0.15/idlingengine_0.0.15_darwin_amd64.zip"
      sha256 "dec05edd73867c3f66ad7190a471e4b9aaf5842fd10fc053e67b6e8e00afb798"

      def install
        bin.install "idlingengine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/idlingengine/releases/download/v0.0.15/idlingengine_0.0.15_darwin_arm64.zip"
      sha256 "f85737f55bd59f7e016aa9730ad9de480df9ba05e2aedc30828f2be13e82f8b1"

      def install
        bin.install "idlingengine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idlingengine/releases/download/v0.0.15/idlingengine_0.0.15_linux_amd64.zip"
        sha256 "1a08887582ec5c70ab2d01b6946fe48287bf22b3c0c90f0456cc0c570e3cc679"

        def install
          bin.install "idlingengine"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idlingengine/releases/download/v0.0.15/idlingengine_0.0.15_linux_armv6.zip"
        sha256 "af7ecc6f2581e1683a92d71ffe191043c72042695694ef683a46c16e63059354"

        def install
          bin.install "idlingengine"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/idlingengine/releases/download/v0.0.15/idlingengine_0.0.15_linux_arm64.zip"
        sha256 "243569be2f03e9daca771211b11a6e3a52c6bb5aa936b25db554429992c2c2e1"

        def install
          bin.install "idlingengine"
        end
      end
    end
  end
end
