# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lifelog < Formula
  desc "Track the time you spend on your devices"
  homepage "https://lifelog.dev"
  version "0.1.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/lifelog/releases/download/v0.1.16/lifelog_0.1.16_darwin_amd64.zip"
      sha256 "8593edff8ebd60f942e000c15b07bd33cf7262be7a3b9ebed1daa5138d92a271"

      def install
        bin.install "lifelog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/lifelog/releases/download/v0.1.16/lifelog_0.1.16_darwin_arm64.zip"
      sha256 "6640587ec590d4993e1426a41935fc557d0f07f8f922038c9d9509b685ca72df"

      def install
        bin.install "lifelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/lifelog/releases/download/v0.1.16/lifelog_0.1.16_linux_amd64.zip"
        sha256 "cdecdbd275c4629124d3df048d5122dcff72170fdf259942f2b703a28837426e"

        def install
          bin.install "lifelog"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/lifelog/releases/download/v0.1.16/lifelog_0.1.16_linux_armv6.zip"
        sha256 "3a922cb6ab1a5e9015ef724e71d4849ffe04f415960929ecab5127037318e28e"

        def install
          bin.install "lifelog"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/lifelog/releases/download/v0.1.16/lifelog_0.1.16_linux_arm64.zip"
        sha256 "ee5b5e742233e95b1de067be1e5f46b7014039ff4d060f92cb4df015a5ee2625"

        def install
          bin.install "lifelog"
        end
      end
    end
  end
end
