# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadtoad < Formula
  desc "Load Toad helps you test your web application using HTTP Archive (.har) files"
  homepage "https://loadtoad.kyleu.dev"
  version "0.1.20"
  license "CC0"

  on_macos do
    on_intel do
      url "https://github.com/kyleu/loadtoad/releases/download/v0.1.20/loadtoad_0.1.20_darwin_amd64.zip"
      sha256 "79fd469c41e210bd90304d2d8e70963235bd9fcb38a0127da41eb61cd7d34351"

      def install
        bin.install "loadtoad"
      end
    end
    on_arm do
      url "https://github.com/kyleu/loadtoad/releases/download/v0.1.20/loadtoad_0.1.20_darwin_arm64.zip"
      sha256 "cf3a3898da01734007df8c31dbce4559ebe33f67b04f388e520e1f6d62becdc5"

      def install
        bin.install "loadtoad"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/loadtoad/releases/download/v0.1.20/loadtoad_0.1.20_linux_amd64.zip"
        sha256 "d02ffa377feb5c82429341a3750a9e58eecdf3dbb0184e7647bc0b8cd19caf52"

        def install
          bin.install "loadtoad"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/loadtoad/releases/download/v0.1.20/loadtoad_0.1.20_linux_armv6.zip"
        sha256 "08f7ddc9dcb22e88706fb1714f508f09231e9df34174133522f61dc4ee4ce616"

        def install
          bin.install "loadtoad"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/loadtoad/releases/download/v0.1.20/loadtoad_0.1.20_linux_arm64.zip"
        sha256 "425e3ba3c979eaa1e20c1afc09104714dc2783c408c4d89360f07659a201fe7c"

        def install
          bin.install "loadtoad"
        end
      end
    end
  end
end
