# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadtoad < Formula
  desc "Load Toad helps you test your web application using HTTP Archive (.har) files"
  homepage "https://loadtoad.kyleu.dev"
  version "0.2.6"
  license "CC0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.2.6/loadtoad_0.2.6_darwin_amd64.zip"
      sha256 "d3eaacc0c8270d3f7a68fbe3e65ea807ed22720f104597c437a51e3017ce43af"

      def install
        bin.install "loadtoad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.2.6/loadtoad_0.2.6_darwin_arm64.zip"
      sha256 "9b8d95d76db27c60582c58e29cd0056d8d8d84120b28ff252e20157264763fb5"

      def install
        bin.install "loadtoad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/loadtoad/releases/download/v0.2.6/loadtoad_0.2.6_linux_amd64.zip"
        sha256 "a8188094d5bfc75337967587cf836326ccc3adb7a8bb4a57ba67ed31db07f278"

        def install
          bin.install "loadtoad"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/loadtoad/releases/download/v0.2.6/loadtoad_0.2.6_linux_armv6.zip"
        sha256 "aa478e22f7144524754a151525c5253cfedfaa789e252db728d63c8a387d4196"

        def install
          bin.install "loadtoad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/loadtoad/releases/download/v0.2.6/loadtoad_0.2.6_linux_arm64.zip"
        sha256 "aff114ba87f35319f276100e68175382feb27801b80769d6e46921c670557862"

        def install
          bin.install "loadtoad"
        end
      end
    end
  end
end
