# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadtoad < Formula
  desc "Load Toad helps you test your web application using HTTP Archive (.har) files"
  homepage "https://github.com/kyleu/loadtoad"
  version "0.0.11"
  license "CC0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.0.11/loadtoad_0.0.11_darwin_amd64.zip"
      sha256 "80bb9e32662f6b79eb0bf56687e1b909a8ecf9a8f56239575e994e2e749cfa31"

      def install
        bin.install "loadtoad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.0.11/loadtoad_0.0.11_darwin_arm64.zip"
      sha256 "e2e0c6f178185c98fea4c2a0f88149bafcc03fa8b405d16bccbe2a5cac77be85"

      def install
        bin.install "loadtoad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.0.11/loadtoad_0.0.11_linux_armv6.zip"
      sha256 "269350c356ce4bf058f9cfb1b0e45f3220547766c2a90e9e030c83dc78d4e6e3"

      def install
        bin.install "loadtoad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.0.11/loadtoad_0.0.11_linux_arm64.zip"
      sha256 "b6ebf073a12f6e9813974f8080e3fff309e5267f2807fe3f72d6dddff78303be"

      def install
        bin.install "loadtoad"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/loadtoad/releases/download/v0.0.11/loadtoad_0.0.11_linux_amd64.zip"
      sha256 "1e0c7c562daccc01ab8ac6cebfc750234d245c21a0a0ecc0975860094501d92c"

      def install
        bin.install "loadtoad"
      end
    end
  end
end
