# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Npn < Formula
  desc "It's basically Postman, but much smaller (8MB download) and faster. You can run npn as an HTTP server, or use a native desktop or mobile app."
  homepage "https://github.com/kyleu/npn"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/npn/releases/download/v0.0.6/npn_0.0.6_darwin_arm64.zip"
      sha256 "4c9fbd7c56feb4c77d9ea72b94d339ba988e9162ededb512078bfe43e73220e1"

      def install
        bin.install "npn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/npn/releases/download/v0.0.6/npn_0.0.6_darwin_amd64.zip"
      sha256 "ae9602dd8e1920d76e82944ede3fd380fb6b4132ab9a5ae482c32475b6c443d7"

      def install
        bin.install "npn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/npn/releases/download/v0.0.6/npn_0.0.6_linux_armv6.zip"
      sha256 "dd76501813ca75116116c0457d1cfd72785e67e415069a8f74adaa9d7ce8c923"

      def install
        bin.install "npn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/npn/releases/download/v0.0.6/npn_0.0.6_linux_arm64.zip"
      sha256 "fa749268195d4d498cc7b01e3d20781e0bf4aac62d52569ac980d542b27cb0b4"

      def install
        bin.install "npn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/npn/releases/download/v0.0.6/npn_0.0.6_linux_amd64.zip"
      sha256 "b5c50d6ca44789390ee4ea133f02a3c53354aaf64aa2898ad8099c7cb0124c41"

      def install
        bin.install "npn"
      end
    end
  end
end
