# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Npn < Formula
  desc "It's basically Postman, but much smaller (8MB download) and faster. You can run npn as an HTTP server, or use a native desktop or mobile app."
  homepage "https://github.com/kyleu/npn"
  version "0.2.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/npn/releases/download/v0.2.19/npn_0.2.19_darwin_amd64.zip"
      sha256 "23e68330e4bf240e3c2e7c082f1d9a129b71ed07f86d8af32823ce1db7469267"

      def install
        bin.install "npn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/npn/releases/download/v0.2.19/npn_0.2.19_darwin_arm64.zip"
      sha256 "8593912755c1b10162bb3cb689a595e2caf6282ca0db020f5782818cb2971bfa"

      def install
        bin.install "npn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/npn/releases/download/v0.2.19/npn_0.2.19_linux_amd64.zip"
        sha256 "63eaf0b842e1bf71a47b6c940e721a1e9c3f2ee494789b8d77ae91ca185c278e"

        def install
          bin.install "npn"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/npn/releases/download/v0.2.19/npn_0.2.19_linux_armv6.zip"
        sha256 "7cdfb809044b5cb1cec5fda6e301e55468730946788213f9b4c2693d88aa6fb7"

        def install
          bin.install "npn"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/npn/releases/download/v0.2.19/npn_0.2.19_linux_arm64.zip"
        sha256 "70cb2614fe5f4626e88e0e37587ae014e07f8f4c31b88a843ceaa05a73f1ecf2"

        def install
          bin.install "npn"
        end
      end
    end
  end
end
