# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projectforge < Formula
  desc "Project Forge creates and manages applications written in the Go programming language. Using code generation, the latest technology, and a strong standard library, Project Forge will help manage your project's code, assets, UI and UX."
  homepage "https://projectforge.dev"
  version "1.0.9"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/projectforge/releases/download/v1.0.9/projectforge_1.0.9_darwin_amd64.zip"
      sha256 "58ce346d50e6153cb48026706da2c0f8b15c9ded8e52c9e5ae62620756c2610f"

      def install
        bin.install "projectforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/projectforge/releases/download/v1.0.9/projectforge_1.0.9_darwin_arm64.zip"
      sha256 "6759ebcf1a739337b6ce819a0fb47c9ff1adc342264a4566fc574a81b40e844b"

      def install
        bin.install "projectforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/projectforge/releases/download/v1.0.9/projectforge_1.0.9_linux_arm64.zip"
      sha256 "b6dfb6f25f6726fb0e3ec12e61c50e24feaec00d49be8949439a667adae322af"

      def install
        bin.install "projectforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/projectforge/releases/download/v1.0.9/projectforge_1.0.9_linux_amd64.zip"
      sha256 "959d58c2c328ee707a63137957d4493dfe3b1aad22232c4fa8ab18a259a3b135"

      def install
        bin.install "projectforge"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/projectforge/releases/download/v1.0.9/projectforge_1.0.9_linux_armv6.zip"
      sha256 "cdc5024b7cf7aa6f40644fb165000ef46911688304fb269894d676398779c747"

      def install
        bin.install "projectforge"
      end
    end
  end
end
