# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rituals < Formula
  desc "This app, rituals.dev, allows you to collaborate with your team to manage your work. It provides teams, sprints, estimate sessions, standup meetings, and retrospectives."
  homepage "https://rituals.dev"
  version "2.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.22/rituals_2.0.22_darwin_arm64.zip"
      sha256 "43b97988e527ce5f26e240ae5df46b074203ccf8fb9d21404b5b084ce540e99a"

      def install
        bin.install "rituals"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.22/rituals_2.0.22_darwin_amd64.zip"
      sha256 "e0286f3c32b856aa48c5a8d7add19d6f71b0c1f9822a8a20a8951e271b4ae924"

      def install
        bin.install "rituals"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.22/rituals_2.0.22_linux_amd64.zip"
      sha256 "4e3f7cd67d650ed9cb6a963a1fb4f696c086df5112ce3620bab3406e17550151"

      def install
        bin.install "rituals"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.22/rituals_2.0.22_linux_armv6.zip"
      sha256 "55748c9f89746ab94b8006152fc656ee794ffe84a620cc1c8625cd1d230c2563"

      def install
        bin.install "rituals"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.22/rituals_2.0.22_linux_arm64.zip"
      sha256 "4006c8420912113ffe176e4910a38b635ececfc30a327cfff71842d16bca64c6"

      def install
        bin.install "rituals"
      end
    end
  end
end
