# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rituals < Formula
  desc "This app, rituals.dev, allows you to collaborate with your team to manage your work. It provides teams, sprints, estimate sessions, standup meetings, and retrospectives."
  homepage "https://rituals.dev"
  version "2.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.5/rituals_2.0.5_darwin_arm64.zip"
      sha256 "b3cf3c5ac8b6ce22d1b736fe9699ab9b242d58b1b8af19a7b72cc94561dd0d78"

      def install
        bin.install "rituals"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.5/rituals_2.0.5_darwin_amd64.zip"
      sha256 "a2f9474f9c3cdedf2cdb8cca314a7faeba042645d4250039bf9d2a9657ac9a4d"

      def install
        bin.install "rituals"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.5/rituals_2.0.5_linux_armv6.zip"
      sha256 "5e144509cb43899119b4b263ec62589ebad5f37e09e4286d7f709bc920ad0bca"

      def install
        bin.install "rituals"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.5/rituals_2.0.5_linux_amd64.zip"
      sha256 "29ce4484d34780f881cc5b517deade74cf3a790a046835c5ce047925caf85033"

      def install
        bin.install "rituals"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/rituals/releases/download/v2.0.5/rituals_2.0.5_linux_arm64.zip"
      sha256 "574637258aa7e164f35341c4a05dcdffccd995780f4efdcf9d0c5fa401217c5e"

      def install
        bin.install "rituals"
      end
    end
  end
end
