# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solitaire < Formula
  desc "A solitaire game... details soon"
  homepage "https://github.com/kyleu/solitaire"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/solitaire/releases/download/v0.1.1/solitaire_0.1.1_darwin_amd64.zip"
      sha256 "92bb79abc152110be00257583d4b2074bc17150c44204b208588243f01f5a54f"

      def install
        bin.install "solitaire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/solitaire/releases/download/v0.1.1/solitaire_0.1.1_darwin_arm64.zip"
      sha256 "79583aaa857e5088f7469269b626d601192f7694412162a20f39da3287f1ab66"

      def install
        bin.install "solitaire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/solitaire/releases/download/v0.1.1/solitaire_0.1.1_linux_amd64.zip"
      sha256 "85effc8000b9545fb48643540854edd4c71a89b7bc7184dfe52e39d83c1dbe46"

      def install
        bin.install "solitaire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/solitaire/releases/download/v0.1.1/solitaire_0.1.1_linux_arm64.zip"
      sha256 "0e053286467c874772df131f2721324aa128d0e3131a8537bf67850a39b7b9a4"

      def install
        bin.install "solitaire"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/solitaire/releases/download/v0.1.1/solitaire_0.1.1_linux_armv6.zip"
      sha256 "ebb8bd38a0f3b86306ae6c0b9f887bdf13f555f3838904b092ac67673331cdc2"

      def install
        bin.install "solitaire"
      end
    end
  end
end
