# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solitaire < Formula
  desc "A solitaire game... details soon"
  homepage "https://github.com/kyleu/solitaire"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/solitaire/releases/download/v0.2.7/solitaire_0.2.7_darwin_amd64.zip"
      sha256 "023e4d231eac2a2f94626df517d05e37dc313c927d0fe00889e70fe67abb1c49"

      def install
        bin.install "solitaire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/solitaire/releases/download/v0.2.7/solitaire_0.2.7_darwin_arm64.zip"
      sha256 "b126f9c63635449e8580de1e0c190ca50e5dbee6274926a53819fee0ee539449"

      def install
        bin.install "solitaire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/solitaire/releases/download/v0.2.7/solitaire_0.2.7_linux_amd64.zip"
        sha256 "7d985a740d8ea885119b6dd295d52e392551ed52d8442fa0558c494bcb8399c5"

        def install
          bin.install "solitaire"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/solitaire/releases/download/v0.2.7/solitaire_0.2.7_linux_armv6.zip"
        sha256 "c5ce98b7e4265fb701ceba08ab9d1dddd2ebf5f039fdb05453b5a0ad85074337"

        def install
          bin.install "solitaire"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/solitaire/releases/download/v0.2.7/solitaire_0.2.7_linux_arm64.zip"
        sha256 "abdbfc0056286ae5e2fd092b6b5573e1b0649d7b8cb940113f3d6624fdd78a66"

        def install
          bin.install "solitaire"
        end
      end
    end
  end
end
