# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Spotifriend < Formula
  desc "Your Spotify friend, for everything you'd want to do with your music (a work-in-progress)"
  homepage "https://spotifriend.com"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/spotifriend/releases/download/v0.0.1/spotifriend_0.0.1_darwin_amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0b8f5fd85d2e86e35d10a8747a2cc13f7c32051943ba0e4de3640ebd12d343d0"

      def install
        bin.install "spotifriend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/spotifriend/releases/download/v0.0.1/spotifriend_0.0.1_darwin_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d462e953d77a8e9dc6d75c67bf97c3ae36c23725540b368a2b5cfab3d6ac02fb"

      def install
        bin.install "spotifriend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/spotifriend/releases/download/v0.0.1/spotifriend_0.0.1_linux_amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "ea30fbdff19b2f04ccc3231941d0a9dbb6c95789b7094dab6cf6a0301de400f7"

        def install
          bin.install "spotifriend"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/spotifriend/releases/download/v0.0.1/spotifriend_0.0.1_linux_armv6.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "86bf8256ae6151217acb44ae85668bb4a8504c95a7b41ff543e617baf9bf3b3b"

        def install
          bin.install "spotifriend"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/spotifriend/releases/download/v0.0.1/spotifriend_0.0.1_linux_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "c4a3603f1be0ea0b62edf65e1678a29af46ed9b582e935e690fa8cdfe14d9304"

        def install
          bin.install "spotifriend"
        end
      end
    end
  end
end
