# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Spotifriend < Formula
  desc "Your Spotify friend, for everything you'd want to do with your music (a work-in-progress)"
  homepage "https://spotifriend.com"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/spotifriend/releases/download/v0.0.3/spotifriend_0.0.3_darwin_amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "154c128023767839dd8772c17597a6225c1fbf8652841e1dc1367876971a3a26"

      def install
        bin.install "spotifriend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/spotifriend/releases/download/v0.0.3/spotifriend_0.0.3_darwin_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5262708daacf272d2987bc942667121177b9caf1f65349441105c7cd6e421b5f"

      def install
        bin.install "spotifriend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/spotifriend/releases/download/v0.0.3/spotifriend_0.0.3_linux_amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "de998e3765c54ef76bd00e83e455a06dfd8662c37965861bf788d3e7512dc464"

        def install
          bin.install "spotifriend"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/spotifriend/releases/download/v0.0.3/spotifriend_0.0.3_linux_armv6.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "506a7c180c8dcbf4e65e5ae968b919912af5fe7bd55ac55f43b50e3bc79873fd"

        def install
          bin.install "spotifriend"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyleu/spotifriend/releases/download/v0.0.3/spotifriend_0.0.3_linux_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "ae402e3e8f0dfe111bf6154dbcf403106d8a59422824dbbe9b001a2d1625d8e8"

        def install
          bin.install "spotifriend"
        end
      end
    end
  end
end
