# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todoforge < Formula
  desc "This app is almost entirely generated via Project Forge. It manages collections of todo items, and not much else."
  homepage "https://github.com/kyleu/todoforge"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleu/todoforge/releases/download/v0.1.9/todoforge_0.1.9_darwin_arm64.zip"
      sha256 "34613cedff6ada8c32b8eaa0e0cb5416f6c2617defd5f58f8066d64d14c0130f"

      def install
        bin.install "todoforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/todoforge/releases/download/v0.1.9/todoforge_0.1.9_darwin_amd64.zip"
      sha256 "10ca7de6e3344f12f29002d720123b14c9dcbcfae8558bc72b1981fa5e8125fe"

      def install
        bin.install "todoforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/todoforge/releases/download/v0.1.9/todoforge_0.1.9_linux_armv6.zip"
      sha256 "eaacd4dd0493d25c81d1a26c110553a104ec309dd10567bb5173b62c456da9c3"

      def install
        bin.install "todoforge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyleu/todoforge/releases/download/v0.1.9/todoforge_0.1.9_linux_amd64.zip"
      sha256 "b82426d11b8d049df4d0b60f6d8cdb8999ca94d31b72e89165ee11cfaf20134f"

      def install
        bin.install "todoforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyleu/todoforge/releases/download/v0.1.9/todoforge_0.1.9_linux_arm64.zip"
      sha256 "d196afb29309bef16a026819d892936c639a99acd2163771e0b4321673197725"

      def install
        bin.install "todoforge"
      end
    end
  end
end
